version: '3.8'

services:
  app:
    build: .
    container_name: luckscape_app
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/luckscape/public
    command: bash -c "apache2-foreground"
